//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmxAppServer.Features.Documentation.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Routing_RoutingService_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Routing_RoutingService_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HtmxAppServer.Resources.Routing_RoutingService_fr", typeof(Routing_RoutingService_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        internal static string Missions {
            get {
                return ResourceManager.GetString("Missions", resourceCulture);
            }
        }
        
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        internal static string IdentificationNumbers {
            get {
                return ResourceManager.GetString("IdentificationNumbers", resourceCulture);
            }
        }
        
        internal static string LegalRelations {
            get {
                return ResourceManager.GetString("LegalRelations", resourceCulture);
            }
        }
        
        internal static string FamilyAndLineage {
            get {
                return ResourceManager.GetString("FamilyAndLineage", resourceCulture);
            }
        }
        
        internal static string BCERelations {
            get {
                return ResourceManager.GetString("BCERelations", resourceCulture);
            }
        }
        
        internal static string LoggingMutations {
            get {
                return ResourceManager.GetString("LoggingMutations", resourceCulture);
            }
        }
        
        internal static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        internal static string AffiliationHistory {
            get {
                return ResourceManager.GetString("AffiliationHistory", resourceCulture);
            }
        }
        
        internal static string AssistanceRequests {
            get {
                return ResourceManager.GetString("AssistanceRequests", resourceCulture);
            }
        }
        
        internal static string CareerManagement {
            get {
                return ResourceManager.GetString("CareerManagement", resourceCulture);
            }
        }
        
        internal static string HelpersAndSupported {
            get {
                return ResourceManager.GetString("HelpersAndSupported", resourceCulture);
            }
        }
        
        internal static string ContributionsOverview {
            get {
                return ResourceManager.GetString("ContributionsOverview", resourceCulture);
            }
        }
        
        internal static string EClipz {
            get {
                return ResourceManager.GetString("EClipz", resourceCulture);
            }
        }
        
        internal static string EUTransfer {
            get {
                return ResourceManager.GetString("EUTransfer", resourceCulture);
            }
        }
        
        internal static string Revenues {
            get {
                return ResourceManager.GetString("Revenues", resourceCulture);
            }
        }
        
        internal static string PensionEngineCareer {
            get {
                return ResourceManager.GetString("PensionEngineCareer", resourceCulture);
            }
        }
        
        internal static string CareerCertificate {
            get {
                return ResourceManager.GetString("CareerCertificate", resourceCulture);
            }
        }
    }
}
